name: Go


on:
  push:
    branches: [ master ]
    tags:
      - "v1"
  pull_request:
    branches: [ master ]
    tags:
      - 'v1'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v -o ./sock.exe ./sock.go

    - name: Test
      run: go test -v ./sock.go


    - name: Package
      run: |
        7z a -mx9 sock.7z ./sock.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: ${{ contains(github.ref, '-') }}
        draft: false
        files: |
          sock.7z
        body: |
          ## 更新日志
          * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新
          
