name: Go


on:
  push:
    branches: [ master ]
    tags:
      - "v1"
  pull_request:
    branches: [ master ]
    tags:
      - 'v1'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build ./sock.go

    - name: Test
      run: go test ./sock.go


    - name: Package
      run: |
        7z a -mx9 sock.7z ./sock
    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        files: sock.7z
        draft: false
        body: |
          ## 更新日志
          * 这是 GitHub Actions 自动化部署，更新日志应该很快会手动更新
          
